### ISSUE TITLE
 Add COVID-19 database

### ISSUE THREAD

**Issue by mvtodescato** [JeanCHilger/SCAL#25]
The database is in `csv` format and the topics and judgments are in `xml` format. They need to be processed in according to:

- [x] Convert csv to files that REVEAL understands.
- [x] Convert xml's to files that REVEAL understands.

[This site](https://ir.nist.gov/covidSubmit/data.html) contains the database with topics and respective judgments.

**Comment by jeanchilger** [comment]
* File with topics and queries - equivalent to our `{topic}.topic.stemming.txt`: [link](https://ir.nist.gov/covidSubmit/data/topics-rnd1.xml) (**`XML`**);
* File with relevance judgments - equivalent to our `qrels.{topic}.list` : [link](https://ir.nist.gov/covidSubmit/data/qrels-rnd1.txt) (**`TXT`**);
* File with documents' abstracts, titles and ids - equivalent to the contents of our `{topic}.tgz`: [link](https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/latest/metadata.csv) (**`CSV`**);
